
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class PaymentSubmitWindow
	{
		private global::IhildaWallet.PaymentPreviewSubmitWidget paymentpreviewsubmitwidget1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.PaymentSubmitWindow
			this.Name = "IhildaWallet.PaymentSubmitWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Payment Submit Window");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(12));
			// Container child IhildaWallet.PaymentSubmitWindow.Gtk.Container+ContainerChild
			this.paymentpreviewsubmitwidget1 = new global::IhildaWallet.PaymentPreviewSubmitWidget();
			this.paymentpreviewsubmitwidget1.Events = ((global::Gdk.EventMask)(256));
			this.paymentpreviewsubmitwidget1.Name = "paymentpreviewsubmitwidget1";
			this.Add(this.paymentpreviewsubmitwidget1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 844;
			this.DefaultHeight = 405;
			this.Show();
		}
	}
}
