
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class OrderBookWidget
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label27;

		private global::Gtk.HPaned hpaned1;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Label label26;

		private global::IhildaWallet.OrderBookTableWidget orderbooktablewidget1;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Label label25;

		private global::IhildaWallet.OrderBookTableWidget orderbooktablewidget2;

		private global::Gtk.Label infoLabel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.OrderBookWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "IhildaWallet.OrderBookWidget";
			// Container child IhildaWallet.OrderBookWidget.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label27 = new global::Gtk.Label();
			this.label27.Name = "label27";
			this.label27.LabelProp = global::Mono.Unix.Catalog.GetString("<big><b><u>Orderbook</u></b></big>");
			this.label27.UseMarkup = true;
			this.vbox2.Add(this.label27);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label27]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 579;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label26 = new global::Gtk.Label();
			this.label26.Name = "label26";
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString("<b><span font_size=\"xx-large\" fgcolor=\"green\">Buy Order Bids</span></b>");
			this.label26.UseMarkup = true;
			this.vbox3.Add(this.label26);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label26]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.orderbooktablewidget1 = new global::IhildaWallet.OrderBookTableWidget();
			this.orderbooktablewidget1.Events = ((global::Gdk.EventMask)(256));
			this.orderbooktablewidget1.Name = "orderbooktablewidget1";
			this.vbox3.Add(this.orderbooktablewidget1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.orderbooktablewidget1]));
			w3.Position = 1;
			this.hpaned1.Add(this.vbox3);
			global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.vbox3]));
			w4.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label25 = new global::Gtk.Label();
			this.label25.Name = "label25";
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("<b><span fgcolor=\"red\" font_size=\"xx-large\">Sell Order Asks</span></b>");
			this.label25.UseMarkup = true;
			this.vbox4.Add(this.label25);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label25]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.orderbooktablewidget2 = new global::IhildaWallet.OrderBookTableWidget();
			this.orderbooktablewidget2.Events = ((global::Gdk.EventMask)(256));
			this.orderbooktablewidget2.Name = "orderbooktablewidget2";
			this.vbox4.Add(this.orderbooktablewidget2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.orderbooktablewidget2]));
			w6.Position = 1;
			this.hpaned1.Add(this.vbox4);
			this.vbox2.Add(this.hpaned1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hpaned1]));
			w8.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.infoLabel = new global::Gtk.Label();
			this.infoLabel.Name = "infoLabel";
			this.infoLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<span foreground=\"red\">This is an info bar</span>");
			this.infoLabel.UseMarkup = true;
			this.vbox2.Add(this.infoLabel);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.infoLabel]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
