
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class DebuggingOptionsDialogWindow
	{
		private global::Gtk.Notebook notebook1;

		private global::IhildaWallet.DebugTreeWidget debugtreewidget1;

		private global::Gtk.Label label1;

		private global::IhildaWallet.DebugLibraryWidget debuglibrarywidget1;

		private global::Gtk.Label label3;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label4;

		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gtk.TextView textview1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label5;

		private global::Gtk.Button button245;

		private global::Gtk.Label label2;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.DebuggingOptionsDialogWindow
			this.Name = "IhildaWallet.DebuggingOptionsDialogWindow";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child IhildaWallet.DebuggingOptionsDialogWindow.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 2;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.debugtreewidget1 = new global::IhildaWallet.DebugTreeWidget();
			this.debugtreewidget1.Events = ((global::Gdk.EventMask)(256));
			this.debugtreewidget1.Name = "debugtreewidget1";
			this.notebook1.Add(this.debugtreewidget1);
			// Notebook tab
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Ihilda");
			this.notebook1.SetTabLabel(this.debugtreewidget1, this.label1);
			this.label1.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.debuglibrarywidget1 = new global::IhildaWallet.DebugLibraryWidget();
			this.debuglibrarywidget1.Events = ((global::Gdk.EventMask)(256));
			this.debuglibrarywidget1.Name = "debuglibrarywidget1";
			this.notebook1.Add(this.debuglibrarywidget1);
			global::Gtk.Notebook.NotebookChild w3 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.debuglibrarywidget1]));
			w3.Position = 1;
			// Notebook tab
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("RippleLibSharp");
			this.notebook1.SetTabLabel(this.debuglibrarywidget1, this.label3);
			this.label3.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Run key generation tests");
			this.vbox2.Add(this.label4);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label4]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView();
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.textview1.Editable = false;
			this.scrolledwindow1.Add(this.textview1);
			this.vbox2.Add(this.scrolledwindow1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.scrolledwindow1]));
			w6.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("<span fgcolor=\"green\">Click start to begin key derivation test suite</span>");
			this.label5.UseMarkup = true;
			this.hbox1.Add(this.label5);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label5]));
			w7.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button245 = new global::Gtk.Button();
			this.button245.CanFocus = true;
			this.button245.Name = "button245";
			this.button245.UseUnderline = true;
			this.button245.Label = global::Mono.Unix.Catalog.GetString("Start Test");
			this.hbox1.Add(this.button245);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button245]));
			w8.Position = 1;
			w8.Expand = false;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.notebook1.Add(this.vbox2);
			global::Gtk.Notebook.NotebookChild w10 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox2]));
			w10.Position = 2;
			// Notebook tab
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Test Suite");
			this.notebook1.SetTabLabel(this.vbox2, this.label2);
			this.label2.ShowAll();
			w1.Add(this.notebook1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(w1[this.notebook1]));
			w11.Position = 0;
			// Internal child IhildaWallet.DebuggingOptionsDialogWindow.ActionArea
			global::Gtk.HButtonBox w12 = this.ActionArea;
			w12.Name = "dialog1_ActionArea";
			w12.Spacing = 10;
			w12.BorderWidth = ((uint)(5));
			w12.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = global::Mono.Unix.Catalog.GetString("Finished");
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12[this.buttonOk]));
			w13.Expand = false;
			w13.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 546;
			this.DefaultHeight = 436;
			this.Show();
		}
	}
}
