
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class WalletManagerWidget
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action FileAction;

		private global::Gtk.Action NewWalletAction;

		private global::Gtk.Action EditAction;

		private global::Gtk.Action DeleteWalletAction;

		private global::Gtk.Action WalletAction;

		private global::Gtk.Action NewAction;

		private global::Gtk.Action UpgradeAction;

		private global::Gtk.Action EncryptAction;

		private global::Gtk.Action DecryptAction;

		private global::Gtk.Action ImportAction;

		private global::Gtk.Action ExportAction;

		private global::Gtk.Action CommerceAction;

		private global::Gtk.Action TradingMarketAction;

		private global::Gtk.Action MakeAPaymentAction;

		private global::Gtk.Action MarketBotAction;

		private global::Gtk.Action ManageTrustAction;

		private global::Gtk.Action EditWalletAction;

		private global::Gtk.VBox vbox2;

		private global::Gtk.MenuBar menubar1;

		private global::Gtk.HPaned hpaned1;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Label label2;

		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Notebook notebook1;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Button botbutton;

		private global::Gtk.Button tradepairButton;

		private global::Gtk.Button useButton;

		private global::Gtk.Button trustbutton;

		private global::Gtk.Button txbutton;

		private global::Gtk.EventBox eventbox1;

		private global::Gtk.Image image1;

		private global::Gtk.Label label4;

		private global::Gtk.Table table1;

		private global::Gtk.Button button66;

		private global::Gtk.Button button67;

		private global::Gtk.Button deleteButton;

		private global::Gtk.Button editButton;

		private global::Gtk.Button exportButton;

		private global::Gtk.Button importButton;

		private global::Gtk.Button newbutton;

		private global::Gtk.Button upgradebutton;

		private global::Gtk.Label label3;

		private global::Gtk.VBox vbox6;

		private global::Gtk.Button networkbutton1;

		private global::Gtk.Button optionsbutton1;

		private global::Gtk.Button consolebutton1;

		private global::Gtk.Label label1;

		private global::Gtk.Button quitButton;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Label label5;

		private global::IhildaWallet.WalletTree wallettree1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.WalletManagerWidget
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach(this);
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup("Default");
			this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
			w2.Add(this.FileAction, null);
			this.NewWalletAction = new global::Gtk.Action("NewWalletAction", global::Mono.Unix.Catalog.GetString("New Wallet"), null, null);
			this.NewWalletAction.ShortLabel = global::Mono.Unix.Catalog.GetString("New");
			w2.Add(this.NewWalletAction, null);
			this.EditAction = new global::Gtk.Action("EditAction", global::Mono.Unix.Catalog.GetString("Edit"), null, null);
			this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit");
			w2.Add(this.EditAction, null);
			this.DeleteWalletAction = new global::Gtk.Action("DeleteWalletAction", global::Mono.Unix.Catalog.GetString("Delete Wallet"), null, null);
			this.DeleteWalletAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Delete Wallet");
			w2.Add(this.DeleteWalletAction, null);
			this.WalletAction = new global::Gtk.Action("WalletAction", global::Mono.Unix.Catalog.GetString("Wallet..."), null, null);
			this.WalletAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Wallet...");
			w2.Add(this.WalletAction, null);
			this.NewAction = new global::Gtk.Action("NewAction", global::Mono.Unix.Catalog.GetString("New"), null, null);
			this.NewAction.ShortLabel = global::Mono.Unix.Catalog.GetString("New");
			w2.Add(this.NewAction, null);
			this.UpgradeAction = new global::Gtk.Action("UpgradeAction", global::Mono.Unix.Catalog.GetString("Upgrade"), null, null);
			this.UpgradeAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Upgrade");
			w2.Add(this.UpgradeAction, null);
			this.EncryptAction = new global::Gtk.Action("EncryptAction", global::Mono.Unix.Catalog.GetString("Encrypt"), null, null);
			this.EncryptAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Encrypt");
			w2.Add(this.EncryptAction, null);
			this.DecryptAction = new global::Gtk.Action("DecryptAction", global::Mono.Unix.Catalog.GetString("Decrypt"), null, null);
			this.DecryptAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Decrypt");
			w2.Add(this.DecryptAction, null);
			this.ImportAction = new global::Gtk.Action("ImportAction", global::Mono.Unix.Catalog.GetString("Import"), null, null);
			this.ImportAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Import");
			w2.Add(this.ImportAction, null);
			this.ExportAction = new global::Gtk.Action("ExportAction", global::Mono.Unix.Catalog.GetString("Export"), null, null);
			this.ExportAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Export");
			w2.Add(this.ExportAction, null);
			this.CommerceAction = new global::Gtk.Action("CommerceAction", global::Mono.Unix.Catalog.GetString("Commerce"), null, null);
			this.CommerceAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Commerce");
			w2.Add(this.CommerceAction, null);
			this.TradingMarketAction = new global::Gtk.Action("TradingMarketAction", global::Mono.Unix.Catalog.GetString("Trading Market"), null, null);
			this.TradingMarketAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Trade");
			w2.Add(this.TradingMarketAction, null);
			this.MakeAPaymentAction = new global::Gtk.Action("MakeAPaymentAction", global::Mono.Unix.Catalog.GetString("Make a payment"), null, null);
			this.MakeAPaymentAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Make a payment");
			w2.Add(this.MakeAPaymentAction, null);
			this.MarketBotAction = new global::Gtk.Action("MarketBotAction", global::Mono.Unix.Catalog.GetString("Market Bot"), null, null);
			this.MarketBotAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Market Bot");
			w2.Add(this.MarketBotAction, null);
			this.ManageTrustAction = new global::Gtk.Action("ManageTrustAction", global::Mono.Unix.Catalog.GetString("Manage Trust"), null, null);
			this.ManageTrustAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Manage Trust");
			w2.Add(this.ManageTrustAction, null);
			this.EditWalletAction = new global::Gtk.Action("EditWalletAction", global::Mono.Unix.Catalog.GetString("Edit Wallet"), null, null);
			this.EditWalletAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit Wallet");
			w2.Add(this.EditWalletAction, null);
			this.UIManager.InsertActionGroup(w2, 0);
			this.Name = "IhildaWallet.WalletManagerWidget";
			// Container child IhildaWallet.WalletManagerWidget.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menu name='WalletAction' action='WalletAction'><menuitem name='NewAction' action='NewAction'/><menuitem name='EditWalletAction' action='EditWalletAction'/><menuitem name='UpgradeAction' action='UpgradeAction'/><menuitem name='EncryptAction' action='EncryptAction'/><menuitem name='DecryptAction' action='DecryptAction'/><menuitem name='ImportAction' action='ImportAction'/><menuitem name='ExportAction' action='ExportAction'/></menu></menu><menu name='EditAction' action='EditAction'/><menu name='CommerceAction' action='CommerceAction'><menuitem name='TradingMarketAction' action='TradingMarketAction'/><menuitem name='MakeAPaymentAction' action='MakeAPaymentAction'/><menuitem name='MarketBotAction' action='MarketBotAction'/><menuitem name='ManageTrustAction' action='ManageTrustAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox2.Add(this.menubar1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.menubar1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 204;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("<span size=\"x-large\"><b>Actions</b></span>");
			this.label2.UseMarkup = true;
			this.vbox1.Add(this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w5 = new global::Gtk.Viewport();
			w5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport1.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			// Container child vbox3.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 3;
			// Container child vbox5.Gtk.Box+BoxChild
			this.botbutton = new global::Gtk.Button();
			this.botbutton.CanFocus = true;
			this.botbutton.Name = "botbutton";
			this.botbutton.UseUnderline = true;
			this.botbutton.Xalign = 0F;
			this.botbutton.Label = global::Mono.Unix.Catalog.GetString("Market Bot");
			this.vbox5.Add(this.botbutton);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.botbutton]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.tradepairButton = new global::Gtk.Button();
			this.tradepairButton.CanFocus = true;
			this.tradepairButton.Name = "tradepairButton";
			this.tradepairButton.UseUnderline = true;
			this.tradepairButton.Xalign = 0F;
			this.tradepairButton.Label = global::Mono.Unix.Catalog.GetString("Trading Market");
			this.vbox5.Add(this.tradepairButton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.tradepairButton]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.useButton = new global::Gtk.Button();
			this.useButton.CanFocus = true;
			this.useButton.Name = "useButton";
			this.useButton.UseUnderline = true;
			this.useButton.Xalign = 0F;
			this.useButton.Label = global::Mono.Unix.Catalog.GetString("Make A _Payment");
			this.vbox5.Add(this.useButton);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.useButton]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.trustbutton = new global::Gtk.Button();
			this.trustbutton.CanFocus = true;
			this.trustbutton.Name = "trustbutton";
			this.trustbutton.UseUnderline = true;
			this.trustbutton.Xalign = 0F;
			this.trustbutton.Label = global::Mono.Unix.Catalog.GetString("Manage _Trust");
			this.vbox5.Add(this.trustbutton);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.trustbutton]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.txbutton = new global::Gtk.Button();
			this.txbutton.CanFocus = true;
			this.txbutton.Name = "txbutton";
			this.txbutton.UseUnderline = true;
			this.txbutton.Xalign = 0F;
			this.txbutton.Label = global::Mono.Unix.Catalog.GetString("View Transactions");
			this.vbox5.Add(this.txbutton);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.txbutton]));
			w10.Position = 4;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.eventbox1 = new global::Gtk.EventBox();
			this.eventbox1.Name = "eventbox1";
			// Container child eventbox1.Gtk.Container+ContainerChild
			this.image1 = new global::Gtk.Image();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("IhildaWallet.Images.ihilda_logo_black_sans_150.png");
			this.eventbox1.Add(this.image1);
			this.vbox5.Add(this.eventbox1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.eventbox1]));
			w12.PackType = ((global::Gtk.PackType)(1));
			w12.Position = 5;
			this.notebook1.Add(this.vbox5);
			// Notebook tab
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Transact</b>");
			this.label4.UseMarkup = true;
			this.notebook1.SetTabLabel(this.vbox5, this.label4);
			this.label4.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.table1 = new global::Gtk.Table(((uint)(8)), ((uint)(1)), true);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(3));
			// Container child table1.Gtk.Table+TableChild
			this.button66 = new global::Gtk.Button();
			this.button66.CanFocus = true;
			this.button66.Name = "button66";
			this.button66.UseUnderline = true;
			this.button66.Xalign = 0F;
			this.button66.Label = global::Mono.Unix.Catalog.GetString("Dec_rypt Wallet");
			this.table1.Add(this.button66);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.button66]));
			w14.TopAttach = ((uint)(4));
			w14.BottomAttach = ((uint)(5));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button67 = new global::Gtk.Button();
			this.button67.CanFocus = true;
			this.button67.Name = "button67";
			this.button67.UseUnderline = true;
			this.button67.Xalign = 0F;
			this.button67.Label = global::Mono.Unix.Catalog.GetString("Encr_ypt Wallet");
			this.table1.Add(this.button67);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.button67]));
			w15.TopAttach = ((uint)(3));
			w15.BottomAttach = ((uint)(4));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.deleteButton = new global::Gtk.Button();
			this.deleteButton.CanFocus = true;
			this.deleteButton.Name = "deleteButton";
			this.deleteButton.UseUnderline = true;
			this.deleteButton.Xalign = 0F;
			this.deleteButton.Label = global::Mono.Unix.Catalog.GetString("_Delete Wallet");
			this.table1.Add(this.deleteButton);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.deleteButton]));
			w16.TopAttach = ((uint)(7));
			w16.BottomAttach = ((uint)(8));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.editButton = new global::Gtk.Button();
			this.editButton.CanFocus = true;
			this.editButton.Name = "editButton";
			this.editButton.UseUnderline = true;
			this.editButton.Xalign = 0F;
			this.editButton.Label = global::Mono.Unix.Catalog.GetString("_Edit Wallet");
			this.table1.Add(this.editButton);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.editButton]));
			w17.TopAttach = ((uint)(1));
			w17.BottomAttach = ((uint)(2));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.exportButton = new global::Gtk.Button();
			this.exportButton.CanFocus = true;
			this.exportButton.Name = "exportButton";
			this.exportButton.UseUnderline = true;
			this.exportButton.Xalign = 0F;
			this.exportButton.Label = global::Mono.Unix.Catalog.GetString("E_xport Wallet");
			this.table1.Add(this.exportButton);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1[this.exportButton]));
			w18.TopAttach = ((uint)(6));
			w18.BottomAttach = ((uint)(7));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.importButton = new global::Gtk.Button();
			this.importButton.CanFocus = true;
			this.importButton.Name = "importButton";
			this.importButton.UseUnderline = true;
			this.importButton.Xalign = 0F;
			this.importButton.Label = global::Mono.Unix.Catalog.GetString("_Import Wallet");
			this.table1.Add(this.importButton);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1[this.importButton]));
			w19.TopAttach = ((uint)(5));
			w19.BottomAttach = ((uint)(6));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.newbutton = new global::Gtk.Button();
			this.newbutton.CanFocus = true;
			this.newbutton.Name = "newbutton";
			this.newbutton.UseUnderline = true;
			this.newbutton.Xalign = 0F;
			this.newbutton.Label = global::Mono.Unix.Catalog.GetString("_New Wallet");
			this.table1.Add(this.newbutton);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1[this.newbutton]));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.upgradebutton = new global::Gtk.Button();
			this.upgradebutton.CanFocus = true;
			this.upgradebutton.Name = "upgradebutton";
			this.upgradebutton.UseUnderline = true;
			this.upgradebutton.Xalign = 0F;
			this.upgradebutton.Label = global::Mono.Unix.Catalog.GetString("_Upgrade Wallet");
			this.table1.Add(this.upgradebutton);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1[this.upgradebutton]));
			w21.TopAttach = ((uint)(2));
			w21.BottomAttach = ((uint)(3));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook1.Add(this.table1);
			global::Gtk.Notebook.NotebookChild w22 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.table1]));
			w22.Position = 1;
			// Notebook tab
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Keys</b>");
			this.label3.UseMarkup = true;
			this.notebook1.SetTabLabel(this.table1, this.label3);
			this.label3.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 3;
			// Container child vbox6.Gtk.Box+BoxChild
			this.networkbutton1 = new global::Gtk.Button();
			this.networkbutton1.CanFocus = true;
			this.networkbutton1.Name = "networkbutton1";
			this.networkbutton1.UseUnderline = true;
			this.networkbutton1.Xalign = 0F;
			this.networkbutton1.Label = global::Mono.Unix.Catalog.GetString("Network _Settings");
			this.vbox6.Add(this.networkbutton1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.networkbutton1]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.optionsbutton1 = new global::Gtk.Button();
			this.optionsbutton1.CanFocus = true;
			this.optionsbutton1.Name = "optionsbutton1";
			this.optionsbutton1.UseUnderline = true;
			this.optionsbutton1.Xalign = 0F;
			this.optionsbutton1.Label = global::Mono.Unix.Catalog.GetString("_Options");
			this.vbox6.Add(this.optionsbutton1);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.optionsbutton1]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.consolebutton1 = new global::Gtk.Button();
			this.consolebutton1.CanFocus = true;
			this.consolebutton1.Name = "consolebutton1";
			this.consolebutton1.UseUnderline = true;
			this.consolebutton1.Xalign = 0F;
			this.consolebutton1.Label = global::Mono.Unix.Catalog.GetString("_Console");
			this.vbox6.Add(this.consolebutton1);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.consolebutton1]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			this.notebook1.Add(this.vbox6);
			global::Gtk.Notebook.NotebookChild w26 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox6]));
			w26.Position = 2;
			// Notebook tab
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Options</b>");
			this.label1.UseMarkup = true;
			this.notebook1.SetTabLabel(this.vbox6, this.label1);
			this.label1.ShowAll();
			this.vbox3.Add(this.notebook1);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.notebook1]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.quitButton = new global::Gtk.Button();
			this.quitButton.CanFocus = true;
			this.quitButton.Name = "quitButton";
			this.quitButton.UseUnderline = true;
			this.quitButton.Xalign = 0F;
			this.quitButton.Label = global::Mono.Unix.Catalog.GetString("_Quit");
			this.vbox3.Add(this.quitButton);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.quitButton]));
			w28.PackType = ((global::Gtk.PackType)(1));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			w5.Add(this.vbox3);
			this.scrolledwindow1.Add(w5);
			this.vbox1.Add(this.scrolledwindow1);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.scrolledwindow1]));
			w31.Position = 1;
			this.hpaned1.Add(this.vbox1);
			global::Gtk.Paned.PanedChild w32 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.vbox1]));
			w32.Resize = false;
			w32.Shrink = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("<span size=\"x-large\"><b>Wallets</b></span>");
			this.label5.UseMarkup = true;
			this.vbox4.Add(this.label5);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label5]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.wallettree1 = new global::IhildaWallet.WalletTree();
			this.wallettree1.Events = ((global::Gdk.EventMask)(256));
			this.wallettree1.Name = "wallettree1";
			this.vbox4.Add(this.wallettree1);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.wallettree1]));
			w34.Position = 1;
			this.hpaned1.Add(this.vbox4);
			this.vbox2.Add(this.hpaned1);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hpaned1]));
			w36.Position = 1;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			w1.SetUiManager(UIManager);
			this.Hide();
		}
	}
}
