
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class WalletSwitchWidget
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.Button button91;

		private global::Gtk.Label label1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.WalletSwitchWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "IhildaWallet.WalletSwitchWidget";
			// Container child IhildaWallet.WalletSwitchWidget.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button91 = new global::Gtk.Button();
			this.button91.CanFocus = true;
			this.button91.Name = "button91";
			this.button91.UseUnderline = true;
			this.button91.Label = global::Mono.Unix.Catalog.GetString("Change Wallet");
			this.hbox1.Add(this.button91);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button91]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.Xpad = 7;
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
			this.label1.Selectable = true;
			this.hbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
			w2.Position = 1;
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
