
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class AccountsViewSelector
	{
		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label4;

		private global::Gtk.ComboBoxEntry comboboxentry1;

		private global::Gtk.Button syncbutton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.AccountsViewSelector
			global::Stetic.BinContainer.Attach(this);
			this.Name = "IhildaWallet.AccountsViewSelector";
			// Container child IhildaWallet.AccountsViewSelector.Gtk.Container+ContainerChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("View Account : ");
			this.hbox3.Add(this.label4);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label4]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.comboboxentry1 = global::Gtk.ComboBoxEntry.NewText();
			this.comboboxentry1.Name = "comboboxentry1";
			this.hbox3.Add(this.comboboxentry1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.comboboxentry1]));
			w2.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.syncbutton = new global::Gtk.Button();
			this.syncbutton.CanFocus = true;
			this.syncbutton.Name = "syncbutton";
			this.syncbutton.UseUnderline = true;
			this.syncbutton.Label = global::Mono.Unix.Catalog.GetString("Refresh");
			this.hbox3.Add(this.syncbutton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.syncbutton]));
			w3.PackType = ((global::Gtk.PackType)(1));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.Add(this.hbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
