
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class TradePairManagerWindow
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.HPaned hpaned1;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Label label2;

		private global::Gtk.Button tradeButton;

		private global::Gtk.Button vieworderbookbutton;

		private global::Gtk.Button depthchartbutton;

		private global::Gtk.Button newtpbutton;

		private global::Gtk.Button editbutton;

		private global::Gtk.Button removetpbutton;

		private global::Gtk.Button nsbutton;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Label label1;

		private global::IhildaWallet.TradePairTree tradepairtree1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.TradePairManagerWindow
			this.Name = "IhildaWallet.TradePairManagerWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("TradePair Manager");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child IhildaWallet.TradePairManagerWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 131;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("<b><u>Actions</u></b>");
			this.label2.UseMarkup = true;
			this.vbox3.Add(this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.tradeButton = new global::Gtk.Button();
			this.tradeButton.CanFocus = true;
			this.tradeButton.Name = "tradeButton";
			this.tradeButton.UseUnderline = true;
			this.tradeButton.Xalign = 0F;
			this.tradeButton.Label = global::Mono.Unix.Catalog.GetString("Trade");
			this.vbox3.Add(this.tradeButton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.tradeButton]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vieworderbookbutton = new global::Gtk.Button();
			this.vieworderbookbutton.CanFocus = true;
			this.vieworderbookbutton.Name = "vieworderbookbutton";
			this.vieworderbookbutton.UseUnderline = true;
			this.vieworderbookbutton.Xalign = 0F;
			this.vieworderbookbutton.Label = global::Mono.Unix.Catalog.GetString("View Orderbook");
			this.vbox3.Add(this.vieworderbookbutton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vieworderbookbutton]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.depthchartbutton = new global::Gtk.Button();
			this.depthchartbutton.CanFocus = true;
			this.depthchartbutton.Name = "depthchartbutton";
			this.depthchartbutton.UseUnderline = true;
			this.depthchartbutton.Xalign = 0F;
			this.depthchartbutton.Label = global::Mono.Unix.Catalog.GetString("View Depth Chart");
			this.vbox3.Add(this.depthchartbutton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.depthchartbutton]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.newtpbutton = new global::Gtk.Button();
			this.newtpbutton.CanFocus = true;
			this.newtpbutton.Name = "newtpbutton";
			this.newtpbutton.UseUnderline = true;
			this.newtpbutton.Xalign = 0F;
			this.newtpbutton.Label = global::Mono.Unix.Catalog.GetString("New Trade Pair");
			this.vbox3.Add(this.newtpbutton);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.newtpbutton]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.editbutton = new global::Gtk.Button();
			this.editbutton.CanFocus = true;
			this.editbutton.Name = "editbutton";
			this.editbutton.UseUnderline = true;
			this.editbutton.Xalign = 0F;
			this.editbutton.Label = global::Mono.Unix.Catalog.GetString("Edit Trade Pair");
			this.vbox3.Add(this.editbutton);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.editbutton]));
			w6.Position = 5;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.removetpbutton = new global::Gtk.Button();
			this.removetpbutton.CanFocus = true;
			this.removetpbutton.Name = "removetpbutton";
			this.removetpbutton.UseUnderline = true;
			this.removetpbutton.Xalign = 0F;
			this.removetpbutton.Label = global::Mono.Unix.Catalog.GetString("Remove Trade Pair");
			this.vbox3.Add(this.removetpbutton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.removetpbutton]));
			w7.Position = 6;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.nsbutton = new global::Gtk.Button();
			this.nsbutton.CanFocus = true;
			this.nsbutton.Name = "nsbutton";
			this.nsbutton.UseUnderline = true;
			this.nsbutton.Xalign = 0F;
			this.nsbutton.Label = global::Mono.Unix.Catalog.GetString("Network Settings");
			this.vbox3.Add(this.nsbutton);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.nsbutton]));
			w8.Position = 7;
			w8.Expand = false;
			w8.Fill = false;
			this.hpaned1.Add(this.vbox3);
			global::Gtk.Paned.PanedChild w9 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.vbox3]));
			w9.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("<b><u>Trade Pairs</u></b>");
			this.label1.UseMarkup = true;
			this.vbox4.Add(this.label1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label1]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.tradepairtree1 = new global::IhildaWallet.TradePairTree();
			this.tradepairtree1.Events = ((global::Gdk.EventMask)(256));
			this.tradepairtree1.Name = "tradepairtree1";
			this.vbox4.Add(this.tradepairtree1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.tradepairtree1]));
			w11.Position = 1;
			this.hpaned1.Add(this.vbox4);
			this.vbox2.Add(this.hpaned1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hpaned1]));
			w13.Position = 0;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 1286;
			this.DefaultHeight = 451;
			this.Show();
		}
	}
}
