
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class DepthChartWindow
	{
		private global::Gtk.VBox vbox2;

		private global::IhildaWallet.DepthChartWidget depthchartwidget1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.DepthChartWindow
			this.Name = "IhildaWallet.DepthChartWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Depth Chart");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child IhildaWallet.DepthChartWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.depthchartwidget1 = new global::IhildaWallet.DepthChartWidget();
			this.depthchartwidget1.Events = ((global::Gdk.EventMask)(256));
			this.depthchartwidget1.Name = "depthchartwidget1";
			this.vbox2.Add(this.depthchartwidget1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.depthchartwidget1]));
			w1.Position = 0;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 679;
			this.DefaultHeight = 315;
			this.Show();
		}
	}
}
