
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class SplashWindow
	{
		private global::Gtk.EventBox eventbox4;

		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox3;

		private global::Gtk.EventBox eventbox2;

		private global::Gtk.Image image56;

		private global::Gtk.EventBox eventbox3;

		private global::Gtk.Image image46;

		private global::Gtk.Image image87;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.SplashWindow
			this.Name = "IhildaWallet.SplashWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("SplashWindow");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource("IhildaWallet.Images.ice_splash.png");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(4));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Resizable = false;
			this.AllowGrow = false;
			this.AcceptFocus = false;
			// Container child IhildaWallet.SplashWindow.Gtk.Container+ContainerChild
			this.eventbox4 = new global::Gtk.EventBox();
			this.eventbox4.Name = "eventbox4";
			// Container child eventbox4.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.eventbox2 = new global::Gtk.EventBox();
			this.eventbox2.Name = "eventbox2";
			// Container child eventbox2.Gtk.Container+ContainerChild
			this.image56 = new global::Gtk.Image();
			this.image56.Name = "image56";
			this.image56.Xpad = 5;
			this.image56.Ypad = 5;
			this.image56.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("IhildaWallet.ihildaplain-100-wide.png");
			this.eventbox2.Add(this.image56);
			this.hbox3.Add(this.eventbox2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.eventbox2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.eventbox3 = new global::Gtk.EventBox();
			this.eventbox3.Name = "eventbox3";
			// Container child eventbox3.Gtk.Container+ContainerChild
			this.image46 = new global::Gtk.Image();
			this.image46.Name = "image46";
			this.image46.Xpad = 5;
			this.image46.Ypad = 5;
			this.image46.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("IhildaWallet.Images.ajax-loader-200x200.gif");
			this.eventbox3.Add(this.image46);
			this.hbox3.Add(this.eventbox3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.eventbox3]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox2.Add(this.hbox3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.image87 = new global::Gtk.Image();
			this.image87.Name = "image87";
			this.image87.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("IhildaWallet.coolio-medium.png");
			this.vbox2.Add(this.image87);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.image87]));
			w6.Position = 1;
			this.eventbox4.Add(this.vbox2);
			this.Add(this.eventbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 600;
			this.DefaultHeight = 570;
			this.Show();
		}
	}
}
