
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class OrderClusterCreateWizard
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.OrderClusterCreateWizard
			this.Name = "IhildaWallet.OrderClusterCreateWizard";
			this.Title = global::Mono.Unix.Catalog.GetString("OrderClusterCreateWizard");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(10));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 433;
			this.DefaultHeight = 226;
			this.Show();
		}
	}
}
