
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class PaymentSubmitWindow
	{
		private global::IhildaWallet.PaymentPreviewSubmitWidget paymentpreviewsubmitwidget1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.PaymentSubmitWindow
			this.Name = "IhildaWallet.PaymentSubmitWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("PaymentSubmitWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child IhildaWallet.PaymentSubmitWindow.Gtk.Container+ContainerChild
			this.paymentpreviewsubmitwidget1 = null;
			this.Add(this.paymentpreviewsubmitwidget1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 1277;
			this.DefaultHeight = 456;
			this.Show();
		}
	}
}
