
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class MassPaymentWidget
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label2;

		private global::Gtk.Table table1;

		private global::Gtk.ComboBox andOrBox;

		private global::Gtk.ComboBoxEntry divAmcomboboxentry;

		private global::Gtk.ComboBoxEntry divCurcomboboxentry;

		private global::Gtk.ComboBoxEntry divIssuercomboboxentry;

		private global::Gtk.CheckButton excludecheckbox;

		private global::Gtk.FileChooserButton filechooserbutton2;

		private global::Gtk.FileChooserButton filechooserbutton3;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.CheckButton includecheckbox;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::Gtk.Label label6;

		private global::Gtk.Label label7;

		private global::Gtk.Label label8;

		private global::Gtk.CheckButton maxcheckbox;

		private global::Gtk.ComboBoxEntry maxcomboboxentry;

		private global::Gtk.CheckButton mincheckbox;

		private global::Gtk.ComboBoxEntry mincomboboxentry;

		private global::Gtk.CheckButton requireTokenCheckbox;

		private global::Gtk.ComboBoxEntry shareIssuerComboboxentry;

		private global::Gtk.ComboBoxEntry sharetickercomboboxentry;

		private global::Gtk.Button button217;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.MassPaymentWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "IhildaWallet.MassPaymentWidget";
			// Container child IhildaWallet.MassPaymentWidget.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("<span size=\"x-large\"><b>Mass Payment</b></span>");
			this.label2.UseMarkup = true;
			this.vbox2.Add(this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(10)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.andOrBox = global::Gtk.ComboBox.NewText();
			this.andOrBox.AppendText(global::Mono.Unix.Catalog.GetString("AND"));
			this.andOrBox.AppendText(global::Mono.Unix.Catalog.GetString("OR"));
			this.andOrBox.Sensitive = false;
			this.andOrBox.Name = "andOrBox";
			this.andOrBox.Active = 0;
			this.table1.Add(this.andOrBox);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.andOrBox]));
			w2.TopAttach = ((uint)(3));
			w2.BottomAttach = ((uint)(4));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.divAmcomboboxentry = global::Gtk.ComboBoxEntry.NewText();
			this.divAmcomboboxentry.Name = "divAmcomboboxentry";
			this.table1.Add(this.divAmcomboboxentry);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.divAmcomboboxentry]));
			w3.TopAttach = ((uint)(9));
			w3.BottomAttach = ((uint)(10));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.divCurcomboboxentry = global::Gtk.ComboBoxEntry.NewText();
			this.divCurcomboboxentry.Name = "divCurcomboboxentry";
			this.table1.Add(this.divCurcomboboxentry);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.divCurcomboboxentry]));
			w4.TopAttach = ((uint)(8));
			w4.BottomAttach = ((uint)(9));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.divIssuercomboboxentry = global::Gtk.ComboBoxEntry.NewText();
			this.divIssuercomboboxentry.Name = "divIssuercomboboxentry";
			this.table1.Add(this.divIssuercomboboxentry);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.divIssuercomboboxentry]));
			w5.TopAttach = ((uint)(7));
			w5.BottomAttach = ((uint)(8));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.excludecheckbox = new global::Gtk.CheckButton();
			this.excludecheckbox.CanFocus = true;
			this.excludecheckbox.Name = "excludecheckbox";
			this.excludecheckbox.Label = global::Mono.Unix.Catalog.GetString("Exclude Accounts");
			this.excludecheckbox.DrawIndicator = true;
			this.excludecheckbox.UseUnderline = true;
			this.table1.Add(this.excludecheckbox);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.excludecheckbox]));
			w6.TopAttach = ((uint)(5));
			w6.BottomAttach = ((uint)(6));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.filechooserbutton2 = new global::Gtk.FileChooserButton(global::Mono.Unix.Catalog.GetString("Select a File"), ((global::Gtk.FileChooserAction)(0)));
			this.filechooserbutton2.Sensitive = false;
			this.filechooserbutton2.Name = "filechooserbutton2";
			this.table1.Add(this.filechooserbutton2);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.filechooserbutton2]));
			w7.TopAttach = ((uint)(4));
			w7.BottomAttach = ((uint)(5));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(3));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.filechooserbutton3 = new global::Gtk.FileChooserButton(global::Mono.Unix.Catalog.GetString("Select a File"), ((global::Gtk.FileChooserAction)(0)));
			this.filechooserbutton3.Sensitive = false;
			this.filechooserbutton3.Name = "filechooserbutton3";
			this.table1.Add(this.filechooserbutton3);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.filechooserbutton3]));
			w8.TopAttach = ((uint)(5));
			w8.BottomAttach = ((uint)(6));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.table1.Add(this.hseparator1);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.hseparator1]));
			w9.TopAttach = ((uint)(6));
			w9.BottomAttach = ((uint)(7));
			w9.RightAttach = ((uint)(3));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.includecheckbox = new global::Gtk.CheckButton();
			this.includecheckbox.CanFocus = true;
			this.includecheckbox.Name = "includecheckbox";
			this.includecheckbox.Label = global::Mono.Unix.Catalog.GetString("Include Accounts");
			this.includecheckbox.DrawIndicator = true;
			this.includecheckbox.UseUnderline = true;
			this.table1.Add(this.includecheckbox);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.includecheckbox]));
			w10.TopAttach = ((uint)(4));
			w10.BottomAttach = ((uint)(5));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label();
			this.label3.Sensitive = false;
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Share Ticker</b>");
			this.label3.UseMarkup = true;
			this.table1.Add(this.label3);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label();
			this.label4.Sensitive = false;
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Share Issuer</b>");
			this.label4.UseMarkup = true;
			this.table1.Add(this.label4);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.label4]));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Dividend Amount</b>");
			this.label6.UseMarkup = true;
			this.table1.Add(this.label6);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.label6]));
			w13.TopAttach = ((uint)(9));
			w13.BottomAttach = ((uint)(10));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Dividend Currency</b>");
			this.label7.UseMarkup = true;
			this.table1.Add(this.label7);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.label7]));
			w14.TopAttach = ((uint)(8));
			w14.BottomAttach = ((uint)(9));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.Xalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Dividend Issuer</b>");
			this.label8.UseMarkup = true;
			this.table1.Add(this.label8);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.label8]));
			w15.TopAttach = ((uint)(7));
			w15.BottomAttach = ((uint)(8));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.maxcheckbox = new global::Gtk.CheckButton();
			this.maxcheckbox.Sensitive = false;
			this.maxcheckbox.CanFocus = true;
			this.maxcheckbox.Name = "maxcheckbox";
			this.maxcheckbox.Label = global::Mono.Unix.Catalog.GetString("Maximum Amount");
			this.maxcheckbox.DrawIndicator = true;
			this.maxcheckbox.UseUnderline = true;
			this.table1.Add(this.maxcheckbox);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.maxcheckbox]));
			w16.TopAttach = ((uint)(3));
			w16.BottomAttach = ((uint)(4));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.maxcomboboxentry = global::Gtk.ComboBoxEntry.NewText();
			this.maxcomboboxentry.Sensitive = false;
			this.maxcomboboxentry.Name = "maxcomboboxentry";
			this.table1.Add(this.maxcomboboxentry);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.maxcomboboxentry]));
			w17.TopAttach = ((uint)(3));
			w17.BottomAttach = ((uint)(4));
			w17.LeftAttach = ((uint)(2));
			w17.RightAttach = ((uint)(3));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.mincheckbox = new global::Gtk.CheckButton();
			this.mincheckbox.Sensitive = false;
			this.mincheckbox.CanFocus = true;
			this.mincheckbox.Name = "mincheckbox";
			this.mincheckbox.Label = global::Mono.Unix.Catalog.GetString("Minimum Amount");
			this.mincheckbox.DrawIndicator = true;
			this.mincheckbox.UseUnderline = true;
			this.table1.Add(this.mincheckbox);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1[this.mincheckbox]));
			w18.TopAttach = ((uint)(2));
			w18.BottomAttach = ((uint)(3));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.mincomboboxentry = global::Gtk.ComboBoxEntry.NewText();
			this.mincomboboxentry.Sensitive = false;
			this.mincomboboxentry.Name = "mincomboboxentry";
			this.table1.Add(this.mincomboboxentry);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1[this.mincomboboxentry]));
			w19.TopAttach = ((uint)(2));
			w19.BottomAttach = ((uint)(3));
			w19.LeftAttach = ((uint)(2));
			w19.RightAttach = ((uint)(3));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.requireTokenCheckbox = new global::Gtk.CheckButton();
			this.requireTokenCheckbox.CanFocus = true;
			this.requireTokenCheckbox.Name = "requireTokenCheckbox";
			this.requireTokenCheckbox.Label = global::Mono.Unix.Catalog.GetString("Require Token");
			this.requireTokenCheckbox.DrawIndicator = true;
			this.requireTokenCheckbox.UseUnderline = true;
			this.table1.Add(this.requireTokenCheckbox);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1[this.requireTokenCheckbox]));
			w20.BottomAttach = ((uint)(3));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.shareIssuerComboboxentry = global::Gtk.ComboBoxEntry.NewText();
			this.shareIssuerComboboxentry.Sensitive = false;
			this.shareIssuerComboboxentry.Name = "shareIssuerComboboxentry";
			this.table1.Add(this.shareIssuerComboboxentry);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1[this.shareIssuerComboboxentry]));
			w21.LeftAttach = ((uint)(2));
			w21.RightAttach = ((uint)(3));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.sharetickercomboboxentry = global::Gtk.ComboBoxEntry.NewText();
			this.sharetickercomboboxentry.Sensitive = false;
			this.sharetickercomboboxentry.Name = "sharetickercomboboxentry";
			this.table1.Add(this.sharetickercomboboxentry);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1[this.sharetickercomboboxentry]));
			w22.TopAttach = ((uint)(1));
			w22.BottomAttach = ((uint)(2));
			w22.LeftAttach = ((uint)(2));
			w22.RightAttach = ((uint)(3));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add(this.table1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.table1]));
			w23.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button217 = new global::Gtk.Button();
			this.button217.CanFocus = true;
			this.button217.Name = "button217";
			this.button217.UseUnderline = true;
			this.button217.Label = global::Mono.Unix.Catalog.GetString("Proceed to Payment Manager ( Send Mass Payment )");
			this.vbox2.Add(this.button217);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.button217]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.label4.Hide();
			this.Hide();
		}
	}
}
