
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class AddressDisplayWidget
	{
		private global::Gtk.HBox hbox2;

		private global::Gtk.Button receivebutton;

		private global::Gtk.Label receiveLabel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.AddressDisplayWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "IhildaWallet.AddressDisplayWidget";
			// Container child IhildaWallet.AddressDisplayWidget.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.receivebutton = new global::Gtk.Button();
			this.receivebutton.CanFocus = true;
			this.receivebutton.Name = "receivebutton";
			this.receivebutton.UseUnderline = true;
			this.receivebutton.Label = global::Mono.Unix.Catalog.GetString("_Receive Address --->");
			this.hbox2.Add(this.receivebutton);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.receivebutton]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.receiveLabel = new global::Gtk.Label();
			this.receiveLabel.WidthRequest = 315;
			this.receiveLabel.Name = "receiveLabel";
			this.receiveLabel.LabelProp = global::Mono.Unix.Catalog.GetString("-- unsynced --");
			this.receiveLabel.Selectable = true;
			this.hbox2.Add(this.receiveLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.receiveLabel]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.Add(this.hbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
