
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class TradePairTree
	{
		private global::Gtk.ScrolledWindow scrolledwindow2;

		private global::Gtk.TreeView treeview1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.TradePairTree
			global::Stetic.BinContainer.Attach(this);
			this.Name = "IhildaWallet.TradePairTree";
			// Container child IhildaWallet.TradePairTree.Gtk.Container+ContainerChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView();
			this.treeview1.CanFocus = true;
			this.treeview1.Name = "treeview1";
			this.scrolledwindow2.Add(this.treeview1);
			this.Add(this.scrolledwindow2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
