
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class NewButtonDialog
	{
		private global::Gtk.ScrolledWindow scrolledwindow2;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Label label2;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label1;

		private global::Gtk.RadioButton randomRadioButton;

		private global::Gtk.RadioButton ScriptRadioButton;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Label label3;

		private global::Gtk.RadioButton secretRadioButton;

		private global::Gtk.RadioButton privateRadioButton;

		private global::Gtk.RadioButton wordListRadioButton;

		private global::Gtk.RadioButton fileRadioButton;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.NewButtonDialog
			this.Name = "IhildaWallet.NewButtonDialog";
			this.Title = global::Mono.Unix.Catalog.GetString("New Wallet");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child IhildaWallet.NewButtonDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			global::Gtk.Viewport w2 = new global::Gtk.Viewport();
			w2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("<b><u>Create a new wallet</u></b>");
			this.label2.UseMarkup = true;
			this.vbox3.Add(this.label2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.vbox3.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hseparator1]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("<u>New </u>");
			this.label1.UseMarkup = true;
			this.vbox2.Add(this.label1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.randomRadioButton = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("new from random"));
			this.randomRadioButton.CanFocus = true;
			this.randomRadioButton.Name = "randomRadioButton";
			this.randomRadioButton.Active = true;
			this.randomRadioButton.DrawIndicator = true;
			this.randomRadioButton.UseUnderline = true;
			this.randomRadioButton.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.vbox2.Add(this.randomRadioButton);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.randomRadioButton]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.ScriptRadioButton = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("new from vanity script"));
			this.ScriptRadioButton.CanFocus = true;
			this.ScriptRadioButton.Name = "ScriptRadioButton";
			this.ScriptRadioButton.DrawIndicator = true;
			this.ScriptRadioButton.UseUnderline = true;
			this.ScriptRadioButton.Group = this.randomRadioButton.Group;
			this.vbox2.Add(this.ScriptRadioButton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.ScriptRadioButton]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.hbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("<u>Import</u>");
			this.label3.UseMarkup = true;
			this.vbox4.Add(this.label3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label3]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.secretRadioButton = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("import from secret seed"));
			this.secretRadioButton.CanFocus = true;
			this.secretRadioButton.Name = "secretRadioButton";
			this.secretRadioButton.DrawIndicator = true;
			this.secretRadioButton.UseUnderline = true;
			this.secretRadioButton.Group = this.randomRadioButton.Group;
			this.vbox4.Add(this.secretRadioButton);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.secretRadioButton]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.privateRadioButton = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("import from private key"));
			this.privateRadioButton.CanFocus = true;
			this.privateRadioButton.Name = "privateRadioButton";
			this.privateRadioButton.DrawIndicator = true;
			this.privateRadioButton.UseUnderline = true;
			this.privateRadioButton.Group = this.randomRadioButton.Group;
			this.vbox4.Add(this.privateRadioButton);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.privateRadioButton]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.wordListRadioButton = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("import from word list"));
			this.wordListRadioButton.CanFocus = true;
			this.wordListRadioButton.Name = "wordListRadioButton";
			this.wordListRadioButton.DrawIndicator = true;
			this.wordListRadioButton.UseUnderline = true;
			this.wordListRadioButton.Group = this.randomRadioButton.Group;
			this.vbox4.Add(this.wordListRadioButton);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.wordListRadioButton]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.fileRadioButton = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("import from file"));
			this.fileRadioButton.CanFocus = true;
			this.fileRadioButton.Name = "fileRadioButton";
			this.fileRadioButton.DrawIndicator = true;
			this.fileRadioButton.UseUnderline = true;
			this.fileRadioButton.Group = this.randomRadioButton.Group;
			this.vbox4.Add(this.fileRadioButton);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.fileRadioButton]));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			this.hbox1.Add(this.vbox4);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox4]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox3.Add(this.hbox1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
			w15.Position = 2;
			w2.Add(this.vbox3);
			this.scrolledwindow2.Add(w2);
			w1.Add(this.scrolledwindow2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(w1[this.scrolledwindow2]));
			w18.Position = 0;
			// Internal child IhildaWallet.NewButtonDialog.ActionArea
			global::Gtk.HButtonBox w19 = this.ActionArea;
			w19.Name = "dialog1_ActionArea";
			w19.Spacing = 10;
			w19.BorderWidth = ((uint)(5));
			w19.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w20 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w19[this.buttonCancel]));
			w20.Expand = false;
			w20.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w21 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w19[this.buttonOk]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 472;
			this.DefaultHeight = 206;
			this.Show();
		}
	}
}
