
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class TradeWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action FileAction;

		private global::Gtk.Action EditAction;

		private global::Gtk.VBox vbox2;

		private global::IhildaWallet.WalletSwitchWidget walletswitchwidget2;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Table table8;

		private global::IhildaWallet.CurrencyWidget currencywidget1;

		private global::IhildaWallet.CurrencyWidget currencywidget2;

		private global::IhildaWallet.SpreadWidget spreadwidget1;

		private global::Gtk.Notebook notebook1;

		private global::Gtk.Notebook notebook;

		private global::IhildaWallet.BuyWidget buywidget1;

		private global::Gtk.Label label29;

		private global::IhildaWallet.CascadedBuyWidget cascadedbuywidget1;

		private global::Gtk.Label label36;

		private global::IhildaWallet.AutomatedBuyWidget automatedbuywidget1;

		private global::Gtk.Label label41;

		private global::Gtk.Label label73;

		private global::Gtk.Notebook notebook4;

		private global::IhildaWallet.SellWidget sellwidget1;

		private global::Gtk.Label label74;

		private global::IhildaWallet.CascadedSellWidget cascadedsellwidget2;

		private global::Gtk.Label label75;

		private global::IhildaWallet.AutomatedSellWidget automatedsellwidget1;

		private global::Gtk.Label label76;

		private global::Gtk.Label label77;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.TradeWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
			this.FileAction.HideIfEmpty = false;
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
			w1.Add(this.FileAction, null);
			this.EditAction = new global::Gtk.Action("EditAction", global::Mono.Unix.Catalog.GetString("Edit"), null, null);
			this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit");
			w1.Add(this.EditAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "IhildaWallet.TradeWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Trade Window");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.BorderWidth = ((uint)(10));
			// Container child IhildaWallet.TradeWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.walletswitchwidget2 = null;
			this.vbox2.Add(this.walletswitchwidget2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.walletswitchwidget2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			// Container child hbox3.Gtk.Box+BoxChild
			this.table8 = new global::Gtk.Table(((uint)(2)), ((uint)(1)), false);
			this.table8.Name = "table8";
			this.table8.RowSpacing = ((uint)(6));
			this.table8.ColumnSpacing = ((uint)(6));
			// Container child table8.Gtk.Table+TableChild
			this.currencywidget1 = null;
			this.table8.Add(this.currencywidget1);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table8[this.currencywidget1]));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.currencywidget2 = null;
			this.table8.Add(this.currencywidget2);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table8[this.currencywidget2]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox3.Add(this.table8);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.table8]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.spreadwidget1 = null;
			this.hbox3.Add(this.spreadwidget1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.spreadwidget1]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox2.Add(this.hbox3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
			w7.Position = 1;
			w7.Expand = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 1;
			this.notebook1.TabPos = ((global::Gtk.PositionType)(0));
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.notebook = new global::Gtk.Notebook();
			this.notebook.CanFocus = true;
			this.notebook.Name = "notebook";
			this.notebook.CurrentPage = 2;
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.buywidget1 = null;
			this.notebook.Add(this.buywidget1);
			// Notebook tab
			this.label29 = new global::Gtk.Label();
			this.label29.Name = "label29";
			this.label29.Xalign = 0F;
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString("Buy");
			this.notebook.SetTabLabel(this.buywidget1, this.label29);
			this.label29.ShowAll();
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.cascadedbuywidget1 = null;
			this.notebook.Add(this.cascadedbuywidget1);
			global::Gtk.Notebook.NotebookChild w9 = ((global::Gtk.Notebook.NotebookChild)(this.notebook[this.cascadedbuywidget1]));
			w9.Position = 1;
			// Notebook tab
			this.label36 = new global::Gtk.Label();
			this.label36.Name = "label36";
			this.label36.Xalign = 0F;
			this.label36.LabelProp = global::Mono.Unix.Catalog.GetString("Cascaded Buy");
			this.notebook.SetTabLabel(this.cascadedbuywidget1, this.label36);
			this.label36.ShowAll();
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.automatedbuywidget1 = null;
			this.notebook.Add(this.automatedbuywidget1);
			global::Gtk.Notebook.NotebookChild w10 = ((global::Gtk.Notebook.NotebookChild)(this.notebook[this.automatedbuywidget1]));
			w10.Position = 2;
			// Notebook tab
			this.label41 = new global::Gtk.Label();
			this.label41.Name = "label41";
			this.label41.LabelProp = global::Mono.Unix.Catalog.GetString("Automated Buy");
			this.notebook.SetTabLabel(this.automatedbuywidget1, this.label41);
			this.label41.ShowAll();
			this.notebook1.Add(this.notebook);
			// Notebook tab
			this.label73 = new global::Gtk.Label();
			this.label73.Name = "label73";
			this.label73.LabelProp = global::Mono.Unix.Catalog.GetString("<span fgcolor=\"green\" size=\"x-large\"><b>Buy</b></span>");
			this.label73.UseMarkup = true;
			this.notebook1.SetTabLabel(this.notebook, this.label73);
			this.label73.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.notebook4 = new global::Gtk.Notebook();
			this.notebook4.CanFocus = true;
			this.notebook4.Name = "notebook4";
			this.notebook4.CurrentPage = 2;
			// Container child notebook4.Gtk.Notebook+NotebookChild
			this.sellwidget1 = null;
			this.notebook4.Add(this.sellwidget1);
			// Notebook tab
			this.label74 = new global::Gtk.Label();
			this.label74.Name = "label74";
			this.label74.LabelProp = global::Mono.Unix.Catalog.GetString("Sell");
			this.notebook4.SetTabLabel(this.sellwidget1, this.label74);
			this.label74.ShowAll();
			// Container child notebook4.Gtk.Notebook+NotebookChild
			this.cascadedsellwidget2 = null;
			this.notebook4.Add(this.cascadedsellwidget2);
			global::Gtk.Notebook.NotebookChild w13 = ((global::Gtk.Notebook.NotebookChild)(this.notebook4[this.cascadedsellwidget2]));
			w13.Position = 1;
			// Notebook tab
			this.label75 = new global::Gtk.Label();
			this.label75.Name = "label75";
			this.label75.LabelProp = global::Mono.Unix.Catalog.GetString("Cascaded Sell");
			this.label75.UseMarkup = true;
			this.notebook4.SetTabLabel(this.cascadedsellwidget2, this.label75);
			this.label75.ShowAll();
			// Container child notebook4.Gtk.Notebook+NotebookChild
			this.automatedsellwidget1 = null;
			this.notebook4.Add(this.automatedsellwidget1);
			global::Gtk.Notebook.NotebookChild w14 = ((global::Gtk.Notebook.NotebookChild)(this.notebook4[this.automatedsellwidget1]));
			w14.Position = 2;
			// Notebook tab
			this.label76 = new global::Gtk.Label();
			this.label76.Name = "label76";
			this.label76.LabelProp = global::Mono.Unix.Catalog.GetString("Automated Sell");
			this.label76.UseMarkup = true;
			this.notebook4.SetTabLabel(this.automatedsellwidget1, this.label76);
			this.label76.ShowAll();
			this.notebook1.Add(this.notebook4);
			global::Gtk.Notebook.NotebookChild w15 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.notebook4]));
			w15.Position = 1;
			// Notebook tab
			this.label77 = new global::Gtk.Label();
			this.label77.Name = "label77";
			this.label77.LabelProp = global::Mono.Unix.Catalog.GetString("<span fgcolor=\"red\" size=\"x-large\"><b>Sell</b></span>");
			this.label77.UseMarkup = true;
			this.notebook1.SetTabLabel(this.notebook4, this.label77);
			this.label77.ShowAll();
			this.vbox2.Add(this.notebook1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.notebook1]));
			w16.Position = 2;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 554;
			this.DefaultHeight = 611;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		}
	}
}
