
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class TradeWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action FileAction;

		private global::Gtk.Action EditAction;

		private global::Gtk.VBox vbox2;

		private global::IhildaWallet.WalletSwitchWidget walletswitchwidget2;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Table table8;

		private global::IhildaWallet.CurrencyWidget currencywidget1;

		private global::IhildaWallet.CurrencyWidget currencywidget2;

		private global::IhildaWallet.SpreadWidget spreadwidget1;

		private global::Gtk.Notebook masternotebook;

		private global::Gtk.Notebook buynotebook;

		private global::IhildaWallet.BuyWidget buywidget1;

		private global::Gtk.Label label29;

		private global::IhildaWallet.CascadedBuyWidget cascadedbuywidget1;

		private global::Gtk.Label label36;

		private global::IhildaWallet.AutomatedBuyWidget automatedbuywidget1;

		private global::Gtk.Label label45;

		private global::Gtk.Label label73;

		private global::Gtk.Notebook sellnotebook;

		private global::IhildaWallet.SellWidget sellwidget1;

		private global::Gtk.Label label75;

		private global::IhildaWallet.CascadedSellWidget cascadedsellwidget1;

		private global::Gtk.Label label80;

		private global::IhildaWallet.AutomatedSellWidget automatedsellwidget1;

		private global::Gtk.Label label99;

		private global::Gtk.Label label116;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.TradeWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
			this.FileAction.HideIfEmpty = false;
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
			w1.Add(this.FileAction, null);
			this.EditAction = new global::Gtk.Action("EditAction", global::Mono.Unix.Catalog.GetString("Edit"), null, null);
			this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit");
			w1.Add(this.EditAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "IhildaWallet.TradeWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Trade Window");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.BorderWidth = ((uint)(10));
			// Container child IhildaWallet.TradeWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.walletswitchwidget2 = new global::IhildaWallet.WalletSwitchWidget();
			this.walletswitchwidget2.Events = ((global::Gdk.EventMask)(256));
			this.walletswitchwidget2.Name = "walletswitchwidget2";
			this.vbox2.Add(this.walletswitchwidget2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.walletswitchwidget2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			// Container child hbox3.Gtk.Box+BoxChild
			this.table8 = new global::Gtk.Table(((uint)(2)), ((uint)(1)), false);
			this.table8.Name = "table8";
			this.table8.RowSpacing = ((uint)(6));
			this.table8.ColumnSpacing = ((uint)(6));
			// Container child table8.Gtk.Table+TableChild
			this.currencywidget1 = new global::IhildaWallet.CurrencyWidget();
			this.currencywidget1.Events = ((global::Gdk.EventMask)(256));
			this.currencywidget1.Name = "currencywidget1";
			this.table8.Add(this.currencywidget1);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table8[this.currencywidget1]));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.currencywidget2 = new global::IhildaWallet.CurrencyWidget();
			this.currencywidget2.Events = ((global::Gdk.EventMask)(256));
			this.currencywidget2.Name = "currencywidget2";
			this.table8.Add(this.currencywidget2);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table8[this.currencywidget2]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox3.Add(this.table8);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.table8]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.spreadwidget1 = new global::IhildaWallet.SpreadWidget();
			this.spreadwidget1.Events = ((global::Gdk.EventMask)(256));
			this.spreadwidget1.Name = "spreadwidget1";
			this.hbox3.Add(this.spreadwidget1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.spreadwidget1]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox2.Add(this.hbox3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
			w7.Position = 1;
			w7.Expand = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.masternotebook = new global::Gtk.Notebook();
			this.masternotebook.CanFocus = true;
			this.masternotebook.Name = "masternotebook";
			this.masternotebook.CurrentPage = 1;
			this.masternotebook.TabPos = ((global::Gtk.PositionType)(0));
			// Container child masternotebook.Gtk.Notebook+NotebookChild
			this.buynotebook = new global::Gtk.Notebook();
			this.buynotebook.CanFocus = true;
			this.buynotebook.Name = "buynotebook";
			this.buynotebook.CurrentPage = 2;
			// Container child buynotebook.Gtk.Notebook+NotebookChild
			this.buywidget1 = new global::IhildaWallet.BuyWidget();
			this.buywidget1.Events = ((global::Gdk.EventMask)(256));
			this.buywidget1.Name = "buywidget1";
			this.buynotebook.Add(this.buywidget1);
			// Notebook tab
			this.label29 = new global::Gtk.Label();
			this.label29.Name = "label29";
			this.label29.Xalign = 0F;
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString("Buy");
			this.buynotebook.SetTabLabel(this.buywidget1, this.label29);
			this.label29.ShowAll();
			// Container child buynotebook.Gtk.Notebook+NotebookChild
			this.cascadedbuywidget1 = new global::IhildaWallet.CascadedBuyWidget();
			this.cascadedbuywidget1.Events = ((global::Gdk.EventMask)(256));
			this.cascadedbuywidget1.Name = "cascadedbuywidget1";
			this.buynotebook.Add(this.cascadedbuywidget1);
			global::Gtk.Notebook.NotebookChild w9 = ((global::Gtk.Notebook.NotebookChild)(this.buynotebook[this.cascadedbuywidget1]));
			w9.Position = 1;
			// Notebook tab
			this.label36 = new global::Gtk.Label();
			this.label36.Name = "label36";
			this.label36.Xalign = 0F;
			this.label36.LabelProp = global::Mono.Unix.Catalog.GetString("Cascaded Buy");
			this.buynotebook.SetTabLabel(this.cascadedbuywidget1, this.label36);
			this.label36.ShowAll();
			// Container child buynotebook.Gtk.Notebook+NotebookChild
			this.automatedbuywidget1 = new global::IhildaWallet.AutomatedBuyWidget();
			this.automatedbuywidget1.Events = ((global::Gdk.EventMask)(256));
			this.automatedbuywidget1.Name = "automatedbuywidget1";
			this.buynotebook.Add(this.automatedbuywidget1);
			global::Gtk.Notebook.NotebookChild w10 = ((global::Gtk.Notebook.NotebookChild)(this.buynotebook[this.automatedbuywidget1]));
			w10.Position = 2;
			// Notebook tab
			this.label45 = new global::Gtk.Label();
			this.label45.Name = "label45";
			this.label45.LabelProp = global::Mono.Unix.Catalog.GetString("Automated Buy");
			this.buynotebook.SetTabLabel(this.automatedbuywidget1, this.label45);
			this.label45.ShowAll();
			this.masternotebook.Add(this.buynotebook);
			// Notebook tab
			this.label73 = new global::Gtk.Label();
			this.label73.Name = "label73";
			this.label73.LabelProp = global::Mono.Unix.Catalog.GetString("<span fgcolor=\"green\" size=\"x-large\"><b>Buy</b></span>");
			this.label73.UseMarkup = true;
			this.masternotebook.SetTabLabel(this.buynotebook, this.label73);
			this.label73.ShowAll();
			// Container child masternotebook.Gtk.Notebook+NotebookChild
			this.sellnotebook = new global::Gtk.Notebook();
			this.sellnotebook.CanFocus = true;
			this.sellnotebook.Name = "sellnotebook";
			this.sellnotebook.CurrentPage = 0;
			// Container child sellnotebook.Gtk.Notebook+NotebookChild
			this.sellwidget1 = new global::IhildaWallet.SellWidget();
			this.sellwidget1.Events = ((global::Gdk.EventMask)(256));
			this.sellwidget1.Name = "sellwidget1";
			this.sellnotebook.Add(this.sellwidget1);
			// Notebook tab
			this.label75 = new global::Gtk.Label();
			this.label75.Name = "label75";
			this.label75.LabelProp = global::Mono.Unix.Catalog.GetString("Sell");
			this.sellnotebook.SetTabLabel(this.sellwidget1, this.label75);
			this.label75.ShowAll();
			// Container child sellnotebook.Gtk.Notebook+NotebookChild
			this.cascadedsellwidget1 = new global::IhildaWallet.CascadedSellWidget();
			this.cascadedsellwidget1.Events = ((global::Gdk.EventMask)(256));
			this.cascadedsellwidget1.Name = "cascadedsellwidget1";
			this.sellnotebook.Add(this.cascadedsellwidget1);
			global::Gtk.Notebook.NotebookChild w13 = ((global::Gtk.Notebook.NotebookChild)(this.sellnotebook[this.cascadedsellwidget1]));
			w13.Position = 1;
			// Notebook tab
			this.label80 = new global::Gtk.Label();
			this.label80.Name = "label80";
			this.label80.LabelProp = global::Mono.Unix.Catalog.GetString("Cascaded Sell");
			this.label80.UseMarkup = true;
			this.sellnotebook.SetTabLabel(this.cascadedsellwidget1, this.label80);
			this.label80.ShowAll();
			// Container child sellnotebook.Gtk.Notebook+NotebookChild
			this.automatedsellwidget1 = new global::IhildaWallet.AutomatedSellWidget();
			this.automatedsellwidget1.Events = ((global::Gdk.EventMask)(256));
			this.automatedsellwidget1.Name = "automatedsellwidget1";
			this.sellnotebook.Add(this.automatedsellwidget1);
			global::Gtk.Notebook.NotebookChild w14 = ((global::Gtk.Notebook.NotebookChild)(this.sellnotebook[this.automatedsellwidget1]));
			w14.Position = 2;
			// Notebook tab
			this.label99 = new global::Gtk.Label();
			this.label99.Name = "label99";
			this.label99.LabelProp = global::Mono.Unix.Catalog.GetString("Automated Sell");
			this.label99.UseMarkup = true;
			this.sellnotebook.SetTabLabel(this.automatedsellwidget1, this.label99);
			this.label99.ShowAll();
			this.masternotebook.Add(this.sellnotebook);
			global::Gtk.Notebook.NotebookChild w15 = ((global::Gtk.Notebook.NotebookChild)(this.masternotebook[this.sellnotebook]));
			w15.Position = 1;
			// Notebook tab
			this.label116 = new global::Gtk.Label();
			this.label116.Name = "label116";
			this.label116.LabelProp = global::Mono.Unix.Catalog.GetString("<span fgcolor=\"red\" size=\"x-large\"><b>Sell</b></span>");
			this.label116.UseMarkup = true;
			this.masternotebook.SetTabLabel(this.sellnotebook, this.label116);
			this.label116.ShowAll();
			this.vbox2.Add(this.masternotebook);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.masternotebook]));
			w16.Position = 2;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 795;
			this.DefaultHeight = 679;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		}
	}
}
