
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class OrderClusterWidget
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.Label label8;

		private global::Gtk.Table table1;

		private global::Gtk.Label ammodlabel;

		private global::Gtk.ComboBoxEntry amountentry;

		private global::Gtk.ComboBoxEntry amountmodentry;

		private global::Gtk.Label label7;

		private global::Gtk.ComboBoxEntry markentry;

		private global::Gtk.Label marklabel;

		private global::Gtk.ComboBoxEntry ordersentry;

		private global::Gtk.Label orderslabel;

		private global::Gtk.ComboBoxEntry pricemodentry;

		private global::Gtk.Label pricemodlabel;

		private global::Gtk.ComboBoxEntry spreadentry;

		private global::Gtk.Label spreadlabel;

		private global::Gtk.Expander expander1;

		private global::Gtk.Label detailslabel;

		private global::Gtk.Label GtkLabel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.OrderClusterWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "IhildaWallet.OrderClusterWidget";
			// Container child IhildaWallet.OrderClusterWidget.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("<span fgcolor=\"red\">Feature not implemented yet</span>");
			this.label8.UseMarkup = true;
			this.vbox3.Add(this.label8);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label8]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(6)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.ammodlabel = new global::Gtk.Label();
			this.ammodlabel.Name = "ammodlabel";
			this.ammodlabel.Xalign = 0F;
			this.ammodlabel.LabelProp = global::Mono.Unix.Catalog.GetString("Amount Modifier");
			this.table1.Add(this.ammodlabel);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.ammodlabel]));
			w2.TopAttach = ((uint)(4));
			w2.BottomAttach = ((uint)(5));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.amountentry = global::Gtk.ComboBoxEntry.NewText();
			this.amountentry.Name = "amountentry";
			this.table1.Add(this.amountentry);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.amountentry]));
			w3.TopAttach = ((uint)(3));
			w3.BottomAttach = ((uint)(4));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.amountmodentry = global::Gtk.ComboBoxEntry.NewText();
			this.amountmodentry.Name = "amountmodentry";
			this.table1.Add(this.amountmodentry);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.amountmodentry]));
			w4.TopAttach = ((uint)(4));
			w4.BottomAttach = ((uint)(5));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Amount");
			this.table1.Add(this.label7);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.label7]));
			w5.TopAttach = ((uint)(3));
			w5.BottomAttach = ((uint)(4));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.markentry = global::Gtk.ComboBoxEntry.NewText();
			this.markentry.Name = "markentry";
			this.table1.Add(this.markentry);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.markentry]));
			w6.TopAttach = ((uint)(5));
			w6.BottomAttach = ((uint)(6));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.marklabel = new global::Gtk.Label();
			this.marklabel.Name = "marklabel";
			this.marklabel.Xalign = 0F;
			this.marklabel.LabelProp = global::Mono.Unix.Catalog.GetString("Mark");
			this.table1.Add(this.marklabel);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.marklabel]));
			w7.TopAttach = ((uint)(5));
			w7.BottomAttach = ((uint)(6));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ordersentry = global::Gtk.ComboBoxEntry.NewText();
			this.ordersentry.Name = "ordersentry";
			this.table1.Add(this.ordersentry);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.ordersentry]));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.orderslabel = new global::Gtk.Label();
			this.orderslabel.Name = "orderslabel";
			this.orderslabel.Xalign = 0F;
			this.orderslabel.LabelProp = global::Mono.Unix.Catalog.GetString("Orders per side");
			this.table1.Add(this.orderslabel);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.orderslabel]));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.pricemodentry = global::Gtk.ComboBoxEntry.NewText();
			this.pricemodentry.Name = "pricemodentry";
			this.table1.Add(this.pricemodentry);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.pricemodentry]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.pricemodlabel = new global::Gtk.Label();
			this.pricemodlabel.Name = "pricemodlabel";
			this.pricemodlabel.Xalign = 0F;
			this.pricemodlabel.LabelProp = global::Mono.Unix.Catalog.GetString("Pricemod");
			this.table1.Add(this.pricemodlabel);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.pricemodlabel]));
			w11.TopAttach = ((uint)(2));
			w11.BottomAttach = ((uint)(3));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.spreadentry = global::Gtk.ComboBoxEntry.NewText();
			this.spreadentry.Name = "spreadentry";
			this.table1.Add(this.spreadentry);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.spreadentry]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.spreadlabel = new global::Gtk.Label();
			this.spreadlabel.Name = "spreadlabel";
			this.spreadlabel.Xalign = 0F;
			this.spreadlabel.LabelProp = global::Mono.Unix.Catalog.GetString("Spread");
			this.table1.Add(this.spreadlabel);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.spreadlabel]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add(this.table1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.table1]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.expander1 = new global::Gtk.Expander(null);
			this.expander1.CanFocus = true;
			this.expander1.Name = "expander1";
			this.expander1.Expanded = true;
			// Container child expander1.Gtk.Container+ContainerChild
			this.detailslabel = new global::Gtk.Label();
			this.detailslabel.Name = "detailslabel";
			this.expander1.Add(this.detailslabel);
			this.GtkLabel = new global::Gtk.Label();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Details");
			this.GtkLabel.UseUnderline = true;
			this.expander1.LabelWidget = this.GtkLabel;
			this.vbox3.Add(this.expander1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.expander1]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			this.Add(this.vbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
