
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class WalletViewWindow
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Notebook notebook1;

		private global::IhildaWallet.WalletShowWidget walletshowwidget1;

		private global::Gtk.Label label4;

		private global::IhildaWallet.BalanceTab balancetab1;

		private global::Gtk.Label label5;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.WalletViewWindow
			this.Name = "IhildaWallet.WalletViewWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("WalletViewWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child IhildaWallet.WalletViewWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.walletshowwidget1 = new global::IhildaWallet.WalletShowWidget();
			this.walletshowwidget1.Events = ((global::Gdk.EventMask)(256));
			this.walletshowwidget1.Name = "walletshowwidget1";
			this.notebook1.Add(this.walletshowwidget1);
			// Notebook tab
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Wallet");
			this.notebook1.SetTabLabel(this.walletshowwidget1, this.label4);
			this.label4.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.balancetab1 = new global::IhildaWallet.BalanceTab();
			this.balancetab1.Events = ((global::Gdk.EventMask)(256));
			this.balancetab1.Name = "balancetab1";
			this.notebook1.Add(this.balancetab1);
			global::Gtk.Notebook.NotebookChild w2 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.balancetab1]));
			w2.Position = 1;
			// Notebook tab
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Balances");
			this.notebook1.SetTabLabel(this.balancetab1, this.label5);
			this.label5.ShowAll();
			this.vbox2.Add(this.notebook1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.notebook1]));
			w3.Position = 0;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 675;
			this.DefaultHeight = 432;
			this.Show();
		}
	}
}
