
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class OptionsWindow
	{
		private global::IhildaWallet.OptionsWidget optionswidget2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.OptionsWindow
			this.Name = "IhildaWallet.OptionsWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("OptionsWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.BorderWidth = ((uint)(5));
			this.DestroyWithParent = true;
			// Container child IhildaWallet.OptionsWindow.Gtk.Container+ContainerChild
			this.optionswidget2 = null;
			this.Add(this.optionswidget2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 882;
			this.DefaultHeight = 483;
			this.Show();
		}
	}
}
