
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class DebuggingOptionsDialogWindow
	{
		private global::Gtk.Notebook notebook1;

		private global::IhildaWallet.DebugTreeWidget debugtreewidget1;

		private global::Gtk.Label label1;

		private global::IhildaWallet.DebugLibraryWidget debuglibrarywidget1;

		private global::Gtk.Label label2;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.DebuggingOptionsDialogWindow
			this.Name = "IhildaWallet.DebuggingOptionsDialogWindow";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child IhildaWallet.DebuggingOptionsDialogWindow.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 1;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.debugtreewidget1 = new global::IhildaWallet.DebugTreeWidget();
			this.debugtreewidget1.Events = ((global::Gdk.EventMask)(256));
			this.debugtreewidget1.Name = "debugtreewidget1";
			this.notebook1.Add(this.debugtreewidget1);
			// Notebook tab
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Ihilda");
			this.notebook1.SetTabLabel(this.debugtreewidget1, this.label1);
			this.label1.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.debuglibrarywidget1 = new global::IhildaWallet.DebugLibraryWidget();
			this.debuglibrarywidget1.Events = ((global::Gdk.EventMask)(256));
			this.debuglibrarywidget1.Name = "debuglibrarywidget1";
			this.notebook1.Add(this.debuglibrarywidget1);
			global::Gtk.Notebook.NotebookChild w3 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.debuglibrarywidget1]));
			w3.Position = 1;
			// Notebook tab
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("RippleLibSharp");
			this.notebook1.SetTabLabel(this.debuglibrarywidget1, this.label2);
			this.label2.ShowAll();
			w1.Add(this.notebook1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1[this.notebook1]));
			w4.Position = 0;
			// Internal child IhildaWallet.DebuggingOptionsDialogWindow.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "dialog1_ActionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = global::Mono.Unix.Catalog.GetString("Finished");
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5[this.buttonOk]));
			w6.Expand = false;
			w6.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 407;
			this.DefaultHeight = 436;
			this.Show();
		}
	}
}
