
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class TransactionSubmitWindow
	{
		private global::Gtk.VBox vbox1;

		private global::IhildaWallet.TransactionSubmitWidget transactionsubmitwidget1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.TransactionSubmitWindow
			this.Name = "IhildaWallet.TransactionSubmitWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("TransactionSubmitWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child IhildaWallet.TransactionSubmitWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.transactionsubmitwidget1 = null;
			this.vbox1.Add(this.transactionsubmitwidget1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.transactionsubmitwidget1]));
			w1.Position = 0;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 549;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
