
// This file has been generated by the GUI designer. Do not modify.
namespace IhildaWallet
{
	public partial class AccountRCLSettingsWindow
	{
		private global::Gtk.VBox vbox2;

		private global::IhildaWallet.WalletSwitchWidget walletswitchwidget1;

		private global::Gtk.Notebook notebook1;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Table table1;

		private global::Gtk.CheckButton clearflagcheckbox;

		private global::Gtk.Entry clearflagentry;

		private global::Gtk.CheckButton domaincheckbutton;

		private global::Gtk.Entry domainentry;

		private global::Gtk.CheckButton emailhashcheckbutton;

		private global::Gtk.Entry emailhashentry;

		private global::Gtk.CheckButton messagekeycheckbutton;

		private global::Gtk.Entry messagekeyentry;

		private global::Gtk.CheckButton setcheckbutton;

		private global::Gtk.Entry setflagentry;

		private global::Gtk.CheckButton ticksizecheckbutton;

		private global::Gtk.Entry ticksizeentry;

		private global::Gtk.CheckButton transferratecheckbutton;

		private global::Gtk.Entry transferrateentry;

		private global::Gtk.Button accountsetbutton;

		private global::Gtk.Label label3;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Table table2;

		private global::Gtk.ComboBoxEntry comboboxentry2;

		private global::Gtk.Label label5;

		private global::Gtk.Button setregularkeybutton;

		private global::Gtk.Label label4;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IhildaWallet.AccountRCLSettingsWindow
			this.Name = "IhildaWallet.AccountRCLSettingsWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("AccountRCLSettingsWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child IhildaWallet.AccountRCLSettingsWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.walletswitchwidget1 = new global::IhildaWallet.WalletSwitchWidget();
			this.walletswitchwidget1.Events = ((global::Gdk.EventMask)(256));
			this.walletswitchwidget1.Name = "walletswitchwidget1";
			this.vbox2.Add(this.walletswitchwidget1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.walletswitchwidget1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(7)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.clearflagcheckbox = new global::Gtk.CheckButton();
			this.clearflagcheckbox.CanFocus = true;
			this.clearflagcheckbox.Name = "clearflagcheckbox";
			this.clearflagcheckbox.Label = global::Mono.Unix.Catalog.GetString("ClearFlag");
			this.clearflagcheckbox.DrawIndicator = true;
			this.clearflagcheckbox.UseUnderline = true;
			this.table1.Add(this.clearflagcheckbox);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.clearflagcheckbox]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.clearflagentry = new global::Gtk.Entry();
			this.clearflagentry.CanFocus = true;
			this.clearflagentry.Name = "clearflagentry";
			this.clearflagentry.IsEditable = true;
			this.clearflagentry.InvisibleChar = '●';
			this.table1.Add(this.clearflagentry);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.clearflagentry]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.domaincheckbutton = new global::Gtk.CheckButton();
			this.domaincheckbutton.CanFocus = true;
			this.domaincheckbutton.Name = "domaincheckbutton";
			this.domaincheckbutton.Label = global::Mono.Unix.Catalog.GetString("Domain");
			this.domaincheckbutton.DrawIndicator = true;
			this.domaincheckbutton.UseUnderline = true;
			this.table1.Add(this.domaincheckbutton);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.domaincheckbutton]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.domainentry = new global::Gtk.Entry();
			this.domainentry.CanFocus = true;
			this.domainentry.Name = "domainentry";
			this.domainentry.IsEditable = true;
			this.domainentry.InvisibleChar = '●';
			this.table1.Add(this.domainentry);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.domainentry]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.emailhashcheckbutton = new global::Gtk.CheckButton();
			this.emailhashcheckbutton.CanFocus = true;
			this.emailhashcheckbutton.Name = "emailhashcheckbutton";
			this.emailhashcheckbutton.Label = global::Mono.Unix.Catalog.GetString("Email Hash");
			this.emailhashcheckbutton.DrawIndicator = true;
			this.emailhashcheckbutton.UseUnderline = true;
			this.table1.Add(this.emailhashcheckbutton);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.emailhashcheckbutton]));
			w6.TopAttach = ((uint)(4));
			w6.BottomAttach = ((uint)(5));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.emailhashentry = new global::Gtk.Entry();
			this.emailhashentry.CanFocus = true;
			this.emailhashentry.Name = "emailhashentry";
			this.emailhashentry.IsEditable = true;
			this.emailhashentry.InvisibleChar = '●';
			this.table1.Add(this.emailhashentry);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.emailhashentry]));
			w7.TopAttach = ((uint)(4));
			w7.BottomAttach = ((uint)(5));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.messagekeycheckbutton = new global::Gtk.CheckButton();
			this.messagekeycheckbutton.CanFocus = true;
			this.messagekeycheckbutton.Name = "messagekeycheckbutton";
			this.messagekeycheckbutton.Label = global::Mono.Unix.Catalog.GetString("Message Key");
			this.messagekeycheckbutton.DrawIndicator = true;
			this.messagekeycheckbutton.UseUnderline = true;
			this.table1.Add(this.messagekeycheckbutton);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.messagekeycheckbutton]));
			w8.TopAttach = ((uint)(5));
			w8.BottomAttach = ((uint)(6));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.messagekeyentry = new global::Gtk.Entry();
			this.messagekeyentry.CanFocus = true;
			this.messagekeyentry.Name = "messagekeyentry";
			this.messagekeyentry.IsEditable = true;
			this.messagekeyentry.InvisibleChar = '●';
			this.table1.Add(this.messagekeyentry);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.messagekeyentry]));
			w9.TopAttach = ((uint)(5));
			w9.BottomAttach = ((uint)(6));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.setcheckbutton = new global::Gtk.CheckButton();
			this.setcheckbutton.CanFocus = true;
			this.setcheckbutton.Name = "setcheckbutton";
			this.setcheckbutton.Label = global::Mono.Unix.Catalog.GetString("SetFlag");
			this.setcheckbutton.DrawIndicator = true;
			this.setcheckbutton.UseUnderline = true;
			this.table1.Add(this.setcheckbutton);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.setcheckbutton]));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.setflagentry = new global::Gtk.Entry();
			this.setflagentry.CanFocus = true;
			this.setflagentry.Name = "setflagentry";
			this.setflagentry.IsEditable = true;
			this.setflagentry.InvisibleChar = '●';
			this.table1.Add(this.setflagentry);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.setflagentry]));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ticksizecheckbutton = new global::Gtk.CheckButton();
			this.ticksizecheckbutton.CanFocus = true;
			this.ticksizecheckbutton.Name = "ticksizecheckbutton";
			this.ticksizecheckbutton.Label = global::Mono.Unix.Catalog.GetString("TickSize");
			this.ticksizecheckbutton.DrawIndicator = true;
			this.ticksizecheckbutton.UseUnderline = true;
			this.table1.Add(this.ticksizecheckbutton);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.ticksizecheckbutton]));
			w12.TopAttach = ((uint)(6));
			w12.BottomAttach = ((uint)(7));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ticksizeentry = new global::Gtk.Entry();
			this.ticksizeentry.CanFocus = true;
			this.ticksizeentry.Name = "ticksizeentry";
			this.ticksizeentry.IsEditable = true;
			this.ticksizeentry.InvisibleChar = '●';
			this.table1.Add(this.ticksizeentry);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.ticksizeentry]));
			w13.TopAttach = ((uint)(6));
			w13.BottomAttach = ((uint)(7));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.transferratecheckbutton = new global::Gtk.CheckButton();
			this.transferratecheckbutton.CanFocus = true;
			this.transferratecheckbutton.Name = "transferratecheckbutton";
			this.transferratecheckbutton.Label = global::Mono.Unix.Catalog.GetString("Transfer Rate");
			this.transferratecheckbutton.DrawIndicator = true;
			this.transferratecheckbutton.UseUnderline = true;
			this.table1.Add(this.transferratecheckbutton);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.transferratecheckbutton]));
			w14.TopAttach = ((uint)(3));
			w14.BottomAttach = ((uint)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.transferrateentry = new global::Gtk.Entry();
			this.transferrateentry.CanFocus = true;
			this.transferrateentry.Name = "transferrateentry";
			this.transferrateentry.IsEditable = true;
			this.transferrateentry.InvisibleChar = '●';
			this.table1.Add(this.transferrateentry);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.transferrateentry]));
			w15.TopAttach = ((uint)(3));
			w15.BottomAttach = ((uint)(4));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox4.Add(this.table1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.table1]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.accountsetbutton = new global::Gtk.Button();
			this.accountsetbutton.CanFocus = true;
			this.accountsetbutton.Name = "accountsetbutton";
			this.accountsetbutton.UseUnderline = true;
			this.accountsetbutton.Label = global::Mono.Unix.Catalog.GetString("Proceed To Transaction Submission ( Account Set )");
			this.vbox4.Add(this.accountsetbutton);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.accountsetbutton]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.notebook1.Add(this.vbox4);
			// Notebook tab
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("AccountSet");
			this.notebook1.SetTabLabel(this.vbox4, this.label3);
			this.label3.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table(((uint)(1)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.comboboxentry2 = global::Gtk.ComboBoxEntry.NewText();
			this.comboboxentry2.Name = "comboboxentry2";
			this.table2.Add(this.comboboxentry2);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table2[this.comboboxentry2]));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Regular Key");
			this.table2.Add(this.label5);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table2[this.label5]));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add(this.table2);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.table2]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.setregularkeybutton = new global::Gtk.Button();
			this.setregularkeybutton.CanFocus = true;
			this.setregularkeybutton.Name = "setregularkeybutton";
			this.setregularkeybutton.UseUnderline = true;
			this.setregularkeybutton.Label = global::Mono.Unix.Catalog.GetString("Proceed To Transaction Submission ( Set Regular Key )");
			this.vbox3.Add(this.setregularkeybutton);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.setregularkeybutton]));
			w22.PackType = ((global::Gtk.PackType)(1));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.notebook1.Add(this.vbox3);
			global::Gtk.Notebook.NotebookChild w23 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox3]));
			w23.Position = 1;
			// Notebook tab
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("SetRegularKey");
			this.notebook1.SetTabLabel(this.vbox3, this.label4);
			this.label4.ShowAll();
			this.vbox2.Add(this.notebook1);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.notebook1]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 508;
			this.DefaultHeight = 344;
			this.Show();
		}
	}
}
